//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormularioHospital2.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public string usuario1 { get; set; }
        public string nombre { get; set; }
        public string contrasena { get; set; }
    }
}
